= README
:toc: auto

image:https://github.com/amineHY/aminehy.github.io/actions/workflows/hugo.yml/badge.svg["Deploy Hugo site to Pages", link="https://github.com/amineHY/aminehy.github.io/actions/workflows/hugo.yml"]

== Installation

* Installation of link:https://go.dev/doc/install[Go]
* Installation of link:https://gohugo.io/installation/linux/[Hugo]



[IMPORTANT]
====
* Make sure to install `Go` first, then install `Hugo`
* Add `env` variable ao `~/.bashrc`

    export PATH=$PATH:/usr/local/go/bin
====

== Run website in development

[source, bash]
----
git clone --recurse-submodules https://github.com/amineHY/aminehy.github.io.git

hugo server --port=8080
----

== Quick start

* link:https://gohugo.io/getting-started/quick-start/[Quick start using Hugo]


* Follow the steps here to create a new hugo website : link:https://gohugo.io/getting-started/quick-start/[Quick Start project]


== Hugo Theme 
* Hugo-Coder : https://github.com/luizdepra/hugo-coder

== Adding content to the website

* Use the command
+
[source]
----
hugo new posts/my-first-post.md
----

* Build the website (including draft posts)
+
[source]
----
hugo server --buildDrafts
hugo server -D
----

== Adding content
Hugo renders the homepage from `content/_index.*`. This repository currently keeps that file empty, so you can either:

- copy an existing page and rename it to `content/_index.adoc` (or `_index.md`) with the desired front matter
- or keep the file empty but use Hugo partials and the `content/common/` fragments to drive the hero/sections that the Hugo Coder theme expects

Once the file exists, edit it with Markdown or Asciidoc to add your hero, headings, lists, images, or Hugo shortcodes just like any other page.


