---
title: "À propos"
date: 2023-03-05T15:04:43+01:00
draft: false
---

:icons: font
include::common/config/config_urls.adoc[]

Je suis un ingénieur chevronné avec une expérience de plus de 10 ans dans le domaine de l'Intelligence Artificielle, spécialisé dans l'ingénierie des solutions, l'analyse de données, le machine learning et la big data. Ma passion pour l'innovation technologique se reflète dans mon engagement à atteindre les objectifs des projets et des clients, tout en adoptant une approche pragmatique.

Mon profil professionnel se distingue par mon adaptabilité, mon esprit d'équipe, ma communication efficace, mon autonomie, mon leadership naturel, ma persévérance et ma gestion efficace du temps. J'ai eu le privilège de collaborer avec des entreprises de renom telles que GreenFlex - Total Énergie, SNCF Réseau, TAG Heuer - LVMH, Drone Volt Group, Institut d'Astrophysique Spatiale, Ecole Polytech Paris Sud, Openclassrooms et M2iFormation.

En tant que formateur, j'ai eu l'opportunité de former plus de 50 consultants issus d'entreprises prestigieuses telles que le Boston Consulting Group, TF1, Bouygues, Sopra Steria, BPCE, Atos et Micropole, notamment sur des sujets tels que Spark, Databricks et la Data Science. En tant que mentor spécialisé en Data Science et Machine Learning, j'ai accompagné plus de 20 professionnels via la plateforme OpenClassrooms. Mon expérience en tant que mentor à l'École Polytech Paris Sud pendant trois ans a renforcé ma capacité à transmettre mes connaissances et à soutenir le développement académique et professionnel des étudiants.

Par ailleurs, j'ai eu l'honneur de publier 8 articles scientifiques dans des journaux internationaux et de présenter mes travaux lors de conférences internationales telles que EUSIPCO, WoSSPA, GRETSI, entre autres.

== Liste de clients

image:{link-logo-greenflex}[height=50]

image:{link-logo-sncf}[height=50]

image:{link-logo-tag}[height=50]

image:{link-logo-dv}[height=50]

image:{link-logo-ias}[height=50]


== Liste de clients dont j'ai formé des ingénieurs

image:{link-logo-atos}[height=50]

image:{link-logo-tf1}[height=50]

image:{link-logo-bouygues}[height=50]

image:{link-logo-decathlon}[height=50]

image:{link-logo-micropole}[height=50]

image:{link-logo-lucy}[height=50]

image:{link-logo-sopra}[height=50]


// == Établissements d'Enseignement

image:{link-logo-m2i}[height=50]

image:{link-logo-oc}[height=50]

image:{link-logo-polytech_psud}[height=50]

image:{link-logo-esi}[height=50]


== Établissements de Formation

image:{link-logo-saclay}[height=50]

image:{link-logo-supelec}[height=50]

image:{link-logo-ets}[height=50]

image:{link-logo-imb}[height=50]

image:{link-logo-ubordeaux}[height=50]

image:{link-logo-enp}[height=50]


== Contactez-moi

Pour discuter de vos besoins en intelligence artificielle ou data science, n'hésitez pas à me contacter par email ou via LinkedIn. Je serai ravi de vous aider à réaliser vos projets !

icon:envelope[link="mailto:hadjyoucef.amine@gmail.com", window=_blanc] Contactez-moi par email

icon:linkedin[link="https://www.linkedin.com/in/aminehy/", window=_blanc] Visitez mon profil LinkedIn
